# Generated by Django 4.2.2 on 2023-06-25 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_brand', models.CharField(max_length=200)),
                ('car_nums', models.CharField(max_length=10)),
                ('car_speed', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100)),
                ('Country_code', models.IntegerField()),
                ('country_size', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Spares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spares_price', models.IntegerField()),
                ('spares_num', models.CharField(max_length=100)),
                ('spares_availability', models.BooleanField()),
            ],
        ),
    ]
