# Generated by Django 4.2.2 on 2023-06-25 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automobile', '0002_spares_for_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='car_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='automobile.car'),
        ),
    ]
