# Generated by Django 4.2.2 on 2023-07-03 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automobile', '0005_rename_country_code_country_сountry_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spare',
            name='for_car',
        ),
        migrations.AddField(
            model_name='car',
            name='for_car',
            field=models.ManyToManyField(to='automobile.car'),
        ),
        migrations.AddField(
            model_name='spare',
            name='spares_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
