# Generated by Django 3.2.20 on 2023-07-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automobile', '0008_alter_car_for_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='for_car',
        ),
        migrations.AddField(
            model_name='car',
            name='car_details',
            field=models.ManyToManyField(to='automobile.Spare'),
        ),
    ]
