# Generated by Django 3.2.20 on 2023-07-18 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automobile', '0009_auto_20230706_1318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='сountry_code',
            new_name='сountry_num',
        ),
    ]
