# Generated by Django 3.2.20 on 2023-07-18 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automobile', '0010_rename_сountry_code_country_сountry_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='сountry_num',
            new_name='country_num',
        ),
    ]
