# Generated by Django 4.2.2 on 2023-06-25 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automobile', '0003_country_car_from'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Spares',
            new_name='Spare',
        ),
    ]
