# Generated by Django 4.2.2 on 2023-06-29 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automobile', '0004_rename_spares_spare'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='Country_code',
            new_name='сountry_code',
        ),
        migrations.RemoveField(
            model_name='country',
            name='car_from',
        ),
        migrations.AddField(
            model_name='car',
            name='country_of_origin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='automobile.country'),
        ),
    ]
