# Generated by Django 4.2.2 on 2023-07-04 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automobile', '0008_alter_car_for_car'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='for_car',
            new_name='car_details',
        ),
    ]
